#!/bin/sh
### lolcommits hook (begin) ###
export LANG="en_CA.UTF-8"
export PATH="/home/jared/.rubies/ruby-2.2.2/bin:/usr/bin:$PATH"
lolcommits --capture -c -a 2 --stealth -g --fork --delay=1
###  lolcommits hook (end)  ###
